# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
    ]
