# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechaFin',
            new_name='fechafin',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechaInicio',
            new_name='fechainicio',
        ),
    ]
