# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20160626_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechafin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechainicio',
            field=models.DateTimeField(),
        ),
    ]
