# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'sprint',
                'verbose_name_plural': 'sprints',
            },
        ),
    ]
