# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='horas_hombre',
            field=models.IntegerField(default=datetime.datetime(2016, 6, 6, 14, 8, 9, 913892, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
