# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='horas_hombre',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
