# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20160626_2345'),
        ('sprint', '0002_sprint_horashombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
    ]
