# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0003_auto_20160618_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='horas_hombre',
            field=models.IntegerField(),
        ),
    ]
