# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserStory', '0001_initial'),
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryEstadoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'TO DO'), ('1', 'DOING'), ('2', 'DONE')], default=0, max_length=1)),
                ('actividad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividad.actividad')),
                ('userStory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStory.UserStory')),
            ],
            options={
                'verbose_name': 'userStoryEstadoActividad',
                'verbose_name_plural': 'userStoryEstadoActividades',
            },
        ),
    ]
