# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserStory', '0006_userstory_sprint'),
        ('actividad', '0002_auto_20160507_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoryEstadoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividad.actividad')),
                ('userStory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStory.UserStory')),
            ],
            options={
                'verbose_name': 'userStoryEstadoActividad',
                'verbose_name_plural': 'userStoryEstadoActividades',
            },
        ),
    ]
