# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStoryEstadoActividad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstoryestadoactividad',
            name='estado',
            field=models.CharField(choices=[('0', 'TO DO'), ('1', 'DOING'), ('2', 'DONE')], default=0, max_length=1),
        ),
    ]
