# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserStoryEstadoActividad', '0001_initial'),
        ('actividad', '0001_initial'),
        ('UserStory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstoryestadoactividad',
            name='actividad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividad.actividad'),
        ),
        migrations.AddField(
            model_name='userstoryestadoactividad',
            name='userStory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStory.UserStory'),
        ),
    ]
