# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, default=None, to='permiso.permiso'),
        ),
    ]
