# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_rol_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='rol',
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.SmallIntegerField(choices=[(1, 'DESARROLLADOR'), (2, 'SCRUM_MASTER'), (3, 'ADMINISTRADOR')], default=3),
        ),
    ]
