# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0005_rol_asignado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
    ]
