# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0006_auto_20160618_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
    ]
