# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0008_auto_20160628_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='permisos_del_rol',
            field=models.ManyToManyField(blank=True, help_text='Especifica permisos del rol', related_name='rol_set', related_query_name='user', to='auth.Permission', verbose_name='permisos_del_rol'),
        ),
    ]
