# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0009_auto_20160628_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='permisos_del_rol',
            new_name='permisosdelrol',
        ),
    ]
