# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adjunto', '0002_adjunto_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjunto',
            name='userStory',
        ),
    ]
