# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('flujo', '0003_remove_flujo_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
    ]
