# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDeFlujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('actividades', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'plantillaDeFlujo',
                'verbose_name_plural': 'plantillaDeFlujos',
            },
        ),
    ]
