# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
            },
        ),
    ]
