# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0002_auto_20160618_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'verbose_name': 'permiso', 'verbose_name_plural': 'permisos'},
        ),
    ]
