# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
        ('plantilla_de_flujo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla_de_flujo',
            name='actividades',
        ),
        migrations.AddField(
            model_name='plantilla_de_flujo',
            name='actividades',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividad.actividad'),
        ),
    ]
