# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla_de_flujo', '0003_remove_plantilla_de_flujo_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla_de_flujo',
            name='actividades',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
