# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'historial',
                'verbose_name_plural': 'historiales',
            },
        ),
    ]
