# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserStory', '0006_userstory_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('userStory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserStory.UserStory')),
            ],
            options={
                'verbose_name': 'historial',
                'verbose_name_plural': 'historiales',
            },
        ),
    ]
