# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adjunto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Historial', '0001_initial'),
        ('Nota', '0001_initial'),
        ('permission', '__first__'),
        ('Sprint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('valorNegocio', models.SmallIntegerField(default=0)),
                ('tiempoEstimado', models.SmallIntegerField(default=0)),
                ('tiempoReal', models.SmallIntegerField(default=0)),
                ('prioridad', models.CharField(choices=[('0', 'Baja'), ('1', 'Media'), ('2', 'Alta')], default=0, max_length=1)),
                ('adjunto', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Adjunto.Adjunto')),
                ('flujo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flujo.flujo')),
                ('historial', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Historial.Historial')),
                ('nota', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nota.Nota')),
                ('sprint', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sprint.Sprint')),
                ('usuario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'userStory',
                'verbose_name_plural': 'userStories',
            },
        ),
    ]
