# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='tiempoEstimado',
            new_name='tiempoestimado',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='tiempoReal',
            new_name='tiemporeal',
        ),
        migrations.RenameField(
            model_name='userstory',
            old_name='valorNegocio',
            new_name='valornegocio',
        ),
    ]
