# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sprint', '0002_sprint_horas_hombre'),
        ('Nota', '0001_initial'),
        ('UserStory', '0001_initial'),
        ('Historial', '0001_initial'),
        ('flujo', '0001_initial'),
        ('Adjunto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='flujo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flujo.flujo'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='historial',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Historial.Historial'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='nota',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nota.Nota'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sprint.Sprint'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
