# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0002_auto_20160627_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'verbose_name': 'userstory', 'verbose_name_plural': 'userstories'},
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='nota',
        ),
    ]
