# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStory', '0002_userstory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstory',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='userstory',
            name='tiempoEstimado',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstory',
            name='tiempoReal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstory',
            name='valorNegocio',
            field=models.SmallIntegerField(default=0),
        ),
    ]
