# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0003_auto_20160627_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrummer.Usuario'),
        ),
    ]
