# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sprint', '0001_initial'),
        ('UserStory', '0005_remove_userstory_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sprint.Sprint'),
        ),
    ]
