# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0002_auto_20160507_0254'),
        ('UserStory', '0006_userstory_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='flujo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flujo.flujo'),
        ),
    ]
