# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0006_userstory_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.CharField(choices=[('1', 'Baja'), ('2', 'Media'), ('3', 'Alta')], default=0, max_length=1),
        ),
    ]
