# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStory', '0007_userstory_flujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='tiempoPrueba',
            field=models.SmallIntegerField(default=0),
        ),
    ]
