# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstory', '0007_auto_20160702_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.CharField(max_length=50),
        ),
    ]
