# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStory', '0009_remove_userstory_tiempoprueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='prioridad',
            field=models.CharField(choices=[('0', 'Baja'), ('1', 'Media'), ('2', 'Alta')], default=0, max_length=1),
        ),
    ]
