# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adjunto', '0003_remove_adjunto_userstory'),
        ('Nota', '0003_remove_nota_userstory'),
        ('Historial', '0002_remove_historial_userstory'),
        ('UserStory', '0010_userstory_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='adjunto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Adjunto.Adjunto'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='historial',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Historial.Historial'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='nota',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nota.Nota'),
        ),
    ]
