# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('orden', models.IntegerField()),
                ('flujo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='permission.flujo')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
            },
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together=set([('flujo', 'orden')]),
        ),
    ]
