# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flujo', '0003_remove_flujo_actividades'),
        ('actividad', '0002_auto_20160507_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='flujo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flujo.flujo'),
        ),
    ]
