# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_auto_20160618_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='flujo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='flujo.flujo'),
        ),
    ]
