# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_auto_20160618_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'actividad', 'verbose_name_plural': 'actividads'},
        ),
    ]
