# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Url')),
            ],
        ),
    ]
