# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrummer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
