# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrummer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=1, verbose_name='Fecha de Fin'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=1, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
