# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrummer', '0002_auto_20160430_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Inicio'),
        ),
    ]
