# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrummer', '0003_auto_20160627_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='created_at',
            new_name='createdat',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='updated_at',
            new_name='updatedat',
        ),
    ]
