# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrummer', '0005_auto_20160430_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fechaInicio',
        ),
    ]
