# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 04:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrummer', '0008_auto_20160701_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='usuario', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
