# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 22:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrummer', '0011_auto_20160502_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
